### ISSUE TITLE
Openssl key cannot use sigtool to sign file

### ISSUE THREAD

**Issue by JohnPatel23** [opencoff/sigtool#1]
Sigtool cannot use openssl key to sign file. 

Steps to reproduce

From shell....
_openssl req -x509 -sha256 -nodes -days 365 -newkey rsa:2048 -keyout test-sign.key -out testsys.crt_

Then, using test-sign.key, try to sign a file
_sigtool sign test-sign.key testfile1.txt_

Returns this error....
"_can't parse YAML: yaml: unmarshal errors: line 1: cannot unmarshal !!str '.....BE..' into sign.serialPrivKey_'

but if I generate a key with sigtool, it's fine.  Need to be able to generate and verify with openssl but sign with sigtool (or vice versa) without errors.

Not sure if this is a bug or I am missing steps.  Thank you.

Env: CentOS7
sigtool build with Go 1.11

**Comment by opencoff** [comment]
Hello,

sigtool is a standalone tool and has no relationship or compatibility with openssl. 

1) Use sigtool to first generate keys:
     sigtool generate -p test-sign

This generates two files: test-sign.pub and test-sign.key; 

2) Sign any file using test-sign.key:
    sigtool sign test-sign.key testfile1.txt

This signs testfile1.txt and write signature to testfile1.txt.sig

Hope this helps,
