### ISSUE TITLE
Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [opencoff/sigtool#13]
Windows 7 x64 user here.
Could you be so kind to generate `.exe` for the rest of us, mere users not developers?

**Comment by opencoff** [comment]
[sigtool-v3.1.3_windows-amd64.tar.gz](https://github.com/opencoff/sigtool/files/13924263/sigtool-v3.1.3_windows-amd64.tar.gz)
[sigtool-v3.1.3_windows-arm64.tar.gz](https://github.com/opencoff/sigtool/files/13924265/sigtool-v3.1.3_windows-arm64.tar.gz)

Please try the binaries attached (built using go 1.21.1 for windows); I put Arm and x86 binaries. If you don't face any issues, I'll push the releases to github.

**Comment by sergeevabc** [comment]
@opencoff, thank you for taking the time to compile this app. I tested amd64 version: it launches, generates keys, signs and verifies files. Alas, it is more complicated than I expected after using [Age](https://github.com/FiloSottile/age). You see, the public key is a file that consists of multiple lines, so you cannot put it, for example, in some forum's signature or profile field.

**Comment by opencoff** [comment]
Sigtool also supports openssh ed25519 pub keys (single line). FYI

**Comment by sergeevabc** [comment]
@opencoff, it's not that obvious at present.
Imagine a forum signature:
_Folks, to verify files I publish here, launch $ sigtool.exe verify a4c...z0f file.ext.sig file.ext_
where _a4c...z0f_ is my public key.
Is it possible?

**Comment by opencoff** [comment]
So, the README clearly says sigtool supports openssh keys.

In any case - I like your suggestion; I added this capability to sigtool 3.2.0. You can now use verify like so:

    sigtool verify  iF84Dymq/bAEnUMK6DRIHWAQDRD8FwDDDfsgFfzdjWM=  file.sig file

You can pick up 3.2.0 via the releases page.

**Comment by sergeevabc** [comment]
@opencoff, README file is written rather by a person who spent a lot of time studying the topic, found the existing tools unsatisfactory and created something more convenient from his point of view. However, from the point of view of an ordinary user, which I am, the instructions still look quite complicated. In particular, I think about OpenSSH key once a year, or even less often, since they are required, for example, on FTP server instead of login-password sequence. I have a how-to tutorial about updating those key. Accordingly, it was not obvious to me that it was possible to take the second line with the prefix `pl` from a public file created by Sigtool and insert it into the command line.
