### ISSUE TITLE
Is there a way to increase the key byte size ?

### ISSUE THREAD

**Issue by 0187773933** [opencoff/sigtool#2]
It seems like it only uses the default 32 bytes. But can't 25519 go up to 521 bytes ?

Or is there a way to import a key generated from `ssh-keygen -t ed25519 -b 521` ?

**Comment by opencoff** [comment]
Ed25519 keys are fixed size. Please read the original ed25519 paper or consult your favorite cryptographer. 

Man ssh-keygen says that “-b” is ignored for ed25519 keys :-)

And yes sigtool supports using keys generated via  ssh-keygen. Sigtool identifies those keys by the ssh comment for that key.
